#!/bin/sh



# SSIDの情報を表示するairportコマンドのパスを変数に代入。
airport_path="/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport"


# 配列変数に必要な情報を取得。配列を確認し、要素がなければofflineと表示して終了。
info=( $(eval "$airport_path" --getinfo | grep -E "^ *(agrCtlRSSI|state|lastTxRate|SSID):" | awk '{print $2}') )
if [[ ${#info[@]} -eq 0 ]]; then
    echo "offline"
    exit 1
fi


# 取得した情報の配列から要素毎に切り出す。
rssi="${info[0]}"   # wifiの電波の強さ
stat="${info[1]}"   # wifiが使えるか
rate="${info[2]}"   # wifiの速度
ssid="${info[3]}"   # wifiのssid名


case "$stat" in
		"running" )
				signals=(▁ ▂ ▄ ▆ █)
				signal=""
				rssi_convert=$(expr 5 - ${rssi} / -20)
				for ((i=0; i < ${rssi_convert}; i++)); do
						signal="${signal}${signals[$i]}"
				done
				airport_info=" #[fg=colour049]${ssid}#[default] ${signal} ${rate}Mbs "
				;;
		"init" )
				airport_info=" #[fg=colour227]...#[default] " ;;
		*      )
				airport_info=" #[fg=colour009] ✘ #[default] " ;;
esac


echo "#[bold]|#[default]${airport_info}#[bold]|#[default] "
